general:
  prefix: "<gold>[<bold><red>RandomDupes</red></bold>]</gold>"

# Donkey Death Dupe
# When a donkey with a chest dies, everything inside the donkey's chest is duped
donkey-death-dupe:
  enable: false

# 1.17 Anvil Dupe
# Check this video on how to do it:
# https://www.youtube.com/watch?v=oSdwwxBgWco
anvil-dupe:
  enable: false

# Lava Dupe
# Requires a hopper and lava above the hopper
lava-dupe:
  enable: false

# Minecart Portal Dupe
# Every chest minecart (except already duped ones) that enters a nether portal will be duplicated
minecart-portal-dupe:
  enable: false

# /dupe Command Dupe (:sick:)
# Dupes the item the player is currently using
# Requires actually nothing, cheap dupe, not recommended
# (NOT IMPLEMENTED YET)
dupe-command:
  enable: false
  cooldown: 0 # In seconds
  needs-permission: false # If enabled, the player will need the "randomdupes.dupe" permission
