name: RandomDupes
description: $description
version: '${version}'

main: io.github.Cherryh4ck.randomDupes.RandomDupes
api-version: '1.21.11'
load: POSTWORLD

authors: [ Cherryh4ck ]

commands:
  randomdupes:
    description: Random Dupes Main command.
    usage: /randomdupes [option]
    permission: randomdupes.main
  dupe:
    description: Dupe command.
    usage: /dupe